package pets;

/**
 *
 * @author BSE-01-0024/2025 Isaac Muendo
 *
 */
// Import the Image class from the java.awt package
import java.awt.Image;
// Import the ImageIcon class from the javax.swing package
import javax.swing.ImageIcon;

// Define a new class named Pet that extends javax.swing.JFrame
public class Pet extends javax.swing.JFrame {

    /**
     * Creates new form Pet
     */
    public Pet() {
        // Initialize the components of the JFrame
        initComponents();

        // Add the bird button to the button group
        buttonGroup.add(birdBtn);
        // Add the cat button to the button group
        buttonGroup.add(catBtn);
        // Add the dog button to the button group
        buttonGroup.add(dogBtn);
        // Add the rabbit button to the button group
        buttonGroup.add(rabbitBtn);
        // Add the pig button to the button group
        buttonGroup.add(pigBtn);

        // Add an action listener to the bird button
        birdBtn.addActionListener(evt -> birdBtnActionPerformed(evt));
        // Add an action listener to the cat button
        catBtn.addActionListener(evt -> catBtnActionPerformed(evt));
        // Add an action listener to the dog button
        dogBtn.addActionListener(evt -> dogBtnActionPerformed(evt));
        // Add an action listener to the rabbit button
        rabbitBtn.addActionListener(evt -> rabbitBtnActionPerformed(evt));
        // Add an action listener to the pig button
        pigBtn.addActionListener(evt -> pigBtnActionPerformed(evt));

        // Set the bird button as the default selection
        birdBtn.setSelected(true);
        // Create a new ImageIcon for the bird image
        ImageIcon birdIcon = new ImageIcon(getClass().getResource("/images/bird.png"));
        // Scale the bird image to fit the display area
        Image birdImage = birdIcon.getImage().getScaledInstance(270, 370, Image.SCALE_SMOOTH);
        // Set the scaled bird image as the icon for the image display
        imageDisplay.setIcon(new ImageIcon(birdImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        birdBtn = new javax.swing.JRadioButton();
        catBtn = new javax.swing.JRadioButton();
        dogBtn = new javax.swing.JRadioButton();
        rabbitBtn = new javax.swing.JRadioButton();
        pigBtn = new javax.swing.JRadioButton();
        imageDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BSE-01-0024/2025: Radio Button Demo");

        birdBtn.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        birdBtn.setLabel("Bird");
        birdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birdBtnActionPerformed(evt);
            }
        });

        catBtn.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        catBtn.setLabel("Cat");
        catBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catBtnActionPerformed(evt);
            }
        });

        dogBtn.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        dogBtn.setText("Dog");
        dogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dogBtnActionPerformed(evt);
            }
        });

        rabbitBtn.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        rabbitBtn.setText("Rabbit");
        rabbitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabbitBtnActionPerformed(evt);
            }
        });

        pigBtn.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        pigBtn.setLabel("Pig");
        pigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pigBtnActionPerformed(evt);
            }
        });

        imageDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catBtn)
                    .addComponent(birdBtn)
                    .addComponent(pigBtn)
                    .addComponent(rabbitBtn)
                    .addComponent(dogBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(imageDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(birdBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(catBtn)
                        .addGap(18, 18, 18)
                        .addComponent(dogBtn)
                        .addGap(18, 18, 18)
                        .addComponent(rabbitBtn)
                        .addGap(18, 18, 18)
                        .addComponent(pigBtn)))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayImage(String imagePath, int width, int height) {
        // Create an ImageIcon object from the specified image resource
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));

        // Scale the image to fit the display area smoothly
        Image image = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);

        // Set the scaled image as the icon for the image display component
        imageDisplay.setIcon(new ImageIcon(image));
    }
    
    // Method to handle the action event when the bird button is clicked
    private void birdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birdBtnActionPerformed
        // Load and display the bird image
        displayImage("/images/bird.png", 270, 370);
    }//GEN-LAST:event_birdBtnActionPerformed
    // Method to handle the action event when the cat button is clicked
    private void catBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catBtnActionPerformed
        // Load and display the cat image
        displayImage("/images/cat.jpg", 370, 370);
    }//GEN-LAST:event_catBtnActionPerformed
    // Method to handle the action event when the dog button is clicked
    private void dogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dogBtnActionPerformed
        // Load and display the dog image
        displayImage("/images/dog.jpg", 370, 370);
    }//GEN-LAST:event_dogBtnActionPerformed
    // Method to handle the action event when the rabbit button is clicked
    private void rabbitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabbitBtnActionPerformed
        // Load and display the rabbit image
        displayImage("/images/rabbit.jpg", 370, 370);
    }//GEN-LAST:event_rabbitBtnActionPerformed
    // Method to handle the action event when the pig button is clicked
    private void pigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pigBtnActionPerformed
        // Load and display the pig image
        displayImage("/images/pig.jpg", 370, 370);
    }//GEN-LAST:event_pigBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton birdBtn;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton catBtn;
    private javax.swing.JRadioButton dogBtn;
    private javax.swing.JLabel imageDisplay;
    private javax.swing.JRadioButton pigBtn;
    private javax.swing.JRadioButton rabbitBtn;
    // End of variables declaration//GEN-END:variables
}
